### ISSUE TITLE
[CT-544] Due to Python 3.10 there is issue while creating docker image error: incompatible type for argument 1 of ‘_Py_HashDouble’

### ISSUE THREAD

**Issue by prathmeshcu** [dbt-labs/dbt-snowflake#142] opened 2022-04-22 10:57 UTC
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

This is using python 3.10 which is having issue with one of the numpy dependency due to which image is not creating

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
<output goes here>
```

**The operating system you're using:**

**The output of `python --version`:**

**Comment by jtcohen6** [comment] 2022-04-22 16:12
@prathmeshcu We're adding official support for Python 3.10 in dbt-core v1.1, which is currently available as a release candidate.

Which version of dbt are you using? Which Docker image are you installing? Is it ours? https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake

**Comment by jtcohen6** [comment] 2022-04-26 10:06
Ah, I think this a duplicate of https://github.com/dbt-labs/dbt-core/issues/5122. I'm going to close this accordingly, but please comment back here if I'm mistaken.

**Closed by jtcohen6** 2022-04-26 10:06 UTC
Labels: bug, duplicate

**Comment by prathmeshcu** [comment] 2022-04-26 10:12
> Ah, I think this a duplicate of [dbt-labs/dbt-core#5122](https://github.com/dbt-labs/dbt-core/issues/5122). I'm going to close this accordingly, but please comment back here if I'm mistaken.

looks to be the same issue please close it
