### ISSUE TITLE
[CT-1344] Unhandled error while executing test - 252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(252732072) for FIXED data

### ISSUE THREAD

**Issue by AnandaRoc360** [dbt-labs/dbt-snowflake#296] opened 2022-10-14 00:19 UTC
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I tried running some dbt generic tests (unique, not_null, ..etc) for dbt-snowflake. I got the below errors

Unhandled error while executing test
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(252732072) for FIXED data

### Expected Behavior

The generic tests should pass without any internal/abnormal errors.

### Steps To Reproduce

1) dbt test -s (model_name)

### Relevant log output

```shell
1 of 2 START test not_null_(model details) ....................... [RUN]
Unhandled error while executing test.(project name).not_null_(model details).4160c5e7fe 
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(160100344) for      FIXED data

2 of 2 START test unique_(model details) ......................... [RUN]
03:31:21  Unhandled error while executing test.(project name).unique_(model details).9b30087e69
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(160100344) for FIXED data
```

### Environment

```markdown
dbt-core       1.2.1
dbt-snowflake  1.2.0
snowflake-connector-python   2.7.8
Python 3.9.12
```

**Comment by jtcohen6** [comment] 2022-10-16 20:07
Closing as a duplicate of https://github.com/dbt-labs/dbt-snowflake/issues/288. From conversation on that issue, it sounds like the root cause here was a behavior change in a recent Snowflake release, which they're working to roll back.

**Closed by jtcohen6** 2022-10-16 20:07 UTC
Labels: bug, triage

**Comment by orzc6** [comment] 2023-02-24 11:34
Is there any update on this case? I just got the same error while trying to run dbt test
