### ISSUE TITLE
[CT-480] seed: Non-atomic update of seed tables

### ISSUE THREAD

**Issue by adamantike** [dbt-labs/dbt-snowflake#135] opened 2022-04-12 20:05 UTC
### Describe the bug
When running `dbt seed`, tables seem to be updated non-atomically, so there's a brief period of time when tables are empty. This could break queries or workflows that are expected to run at the same time as `dbt seed`.

### Steps To Reproduce
1. Copy the contents of [this gist](https://gist.github.com/adamantike/fc8c998232e2cd39033440cec4288611), which includes `requirements.txt`, `dbt_project.yml`, and `profiles.yml`. Configure Snowflake credentials in the `profiles.yml` file.
1. Create a `data` folder, and generate a seeds file with many lines (I have been able to reproduce this issue with small files, but having bigger ones makes reproducibility easier as the table remains empty for more time, while `INSERT`s are being executed):
	```shell
	mkdir -p data/ && \
    	echo "id" > data/test__ids.csv && \
    	for i in `seq 1 1000`; do uuidgen >>data/test__ids.csv; done
	```
1. In a separate shell, trigger the following command to monitor the content of the seed table. Alternatively, the Snowflake web interface can be used to run many `SELECT`s one after another.
	```shell
	while :; do snowsql -o friendly=false -q 'SELECT * FROM "TEST__IDS" LIMIT 1'; done
	```
1. Run the `dbt seed` command in a separate shell:
	```shell
	dbt seed --profiles-dir .
	```

### Expected behavior
The expected behavior would be for the truncate and insert over the seed tables to run atomically, so queries that run at the same time that the `dbt seed` command **not** to receive an empty result set.

### Screenshots and log output
Running the SnowSQL command while `dbt seed` will show that the table is empty sometimes:

```shell
$ while :; do snowsql -o friendly=false -q 'SELECT * FROM "TEST__IDS" LIMIT 1'; done
+--------------------------------------+
| ID                                   |
|--------------------------------------|
| ef4fdfb6-38ee-4b48-b38b-20fbaedc45be |
+--------------------------------------+
1 Row(s) produced. Time Elapsed: 0.268s
+----+
| ID |
|----|
+----+
0 Row(s) produced. Time Elapsed: 0.402s
+--------------------------------------+
| ID                                   |
|--------------------------------------|
| ef4fdfb6-38ee-4b48-b38b-20fbaedc45be |
+--------------------------------------+
1 Row(s) produced. Time Elapsed: 0.382s
```

### System information
**The output of `dbt --version`:**
```
installed version: 1.0.4
   latest version: 1.0.4

Up to date!

Plugins:
  - snowflake: 1.0.0 - Up to date!
```

**The operating system you're using:** Linux (Manjaro)

**The output of `python --version`:** Python 3.7.12 (virtualenv)

**Comment by nathaniel-may** [comment] 2022-04-19 15:41
Hi @adamantike, thanks for your very detailed report. Have you run into any errors or undesired behavior because of this during a `dbt run`? If so, I'd be happy to look at any details you can share on those runs because that would definitely be a bug.

The way dbt orchestrates sending operations to the warehouse, there should never be a time when we query a seed before it's completed. Although you're observing the seed table in an incomplete state, it will never be queried in this state by a any other dbt operations.

**Comment by nathaniel-may** [comment] 2022-04-19 15:47
duplicate of #112

**Closed by nathaniel-may** 2022-04-19 15:47 UTC
Labels: bug, duplicate
