### ISSUE TITLE
[CT-525] First run of model with incremental materialization doesn't use unique_key

### ISSUE THREAD

**Issue by rdbenoit-orennia** [dbt-labs/dbt-snowflake#141] opened 2022-04-20 21:55 UTC
### Describe the bug
A model that has incremental materialization has a unique key parameter that ensures that the unique key is used based on the incremental_strategy. For merge for example a single row will exist based on that unique_key.
The issue is that if the referenced model already has data in it and the incremental model is created for the first time then the unique_key will not be respected and you will end up with duplicates.

### Steps To Reproduce
1. start with base model that has 1 row, key of 'abc'
2. create incremental model that references that base model
3. run incremental model and resulting table will have 1 row with key 'abc'
4. add new row to base model with key of 'abc'
5. run incremental model and table will remain with a single row for key 'abc'
6. re-run incremental model with full-refresh, resulting incremental model table will now have 2 rows each with the key 'abc'

### Expected behavior
1. start with base model that has 1 row, key of 'abc'
2. create incremental model that references that base model
3. run incremental model and resulting table will have 1 row with key 'abc'
4. add new row to base model with key of 'abc'
5. run incremental model and table will remain with a single row for key 'abc'
6. re-run incremental model with full-refresh, resulting incremental model table should only have 1 row with key 'abc'

### Screenshots and log output
None

### Additional context
I'm assuming this has existed for a long time based on inspection of the code and it's unclear to me how to fix as the initial table is created via a create table ....select as statement. But the inconsistency in behaviour must be impacting people I would assume?

**Comment by jtcohen6** [comment] 2022-04-25 08:53
I'm going to close this as a duplicate of dbt-labs/dbt-core#5138, and respond over there, since the question raised in the issue is more broadly applicable (not just Snowflake)

**Closed by jtcohen6** 2022-04-25 08:53 UTC
Labels: bug, duplicate
