### ISSUE TITLE
[ADAP-1054] [CT-3434] [Bug] DBT models with hyphens in filename fail in Snowflake

### ISSUE THREAD

**Issue by jackwellsxyz** [dbt-labs/dbt-snowflake#857] opened 2023-11-29 19:11 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt transpiles a model with a filename containing a hyphen directly into SQL without quoting illegal errors in Snowflake. Here's an example transpiled output that is sent to Snowflake:
```sql
        create or replace transient table MY_DATABASE.MY_SCHEMA.table-with-hyphens
         as
        (
... compiled SQL ...
       );
```

### Expected Behavior

dbt should probably do two things:
* Warn the user that hyphens are not great practice in SQL
* Quote the table name in the CTAS statement such as `create or replace transient table MY_DATABASE.MY_SCHEMA."table-with-hyphens"`

### Steps To Reproduce

1. Create model with a hyphen in the filename, such as `table-with-hyphens.sql`
2. `dbt build --select +table-with-hyphens`

### Relevant log output

```shell
18:17:22    Database Error in model customer-emails (models/tables/customer-emails/customer-emails.sql)
  001003 (42000): SQL compilation error:
  syntax error line 1 at position 66 unexpected '-'.
  compiled Code at target/run/product/models/tables/table-with-hyphens.sql

^^^ Note that the above position (e.g. 66) is dependent on where the hyphens appear in the filename in the generated CTAS statement.
```

### Environment

```markdown
- OS: MacOS Sonoma
- Python: 3.11
- dbt: 1.7.1
```

### Which database adapter are you using with dbt?

snowflake

**Comment by dbeatty10** [comment] 2023-11-30 02:44
Thanks for reaching out about this @jackwellsxyz !

What you observed actually expected behavior, and it is described in the documentation [here](https://docs.getdbt.com/reference/project-configs/quoting#default). You can click between the "Default" and "Snowflake" tabs to see how the quoting behavior for dbt-snowflake differs from other databases.

### Default

<img width="600" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/cad07d67-4d26-40f5-857b-0c67e4e084f0">

### Snowflake

<img width="600" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/d2e8014a-8514-4702-88e2-a389ea675dbc">

### Explanation

The key insight why the default quoting differs for Snowflake is described [here](https://docs.getdbt.com/reference/project-configs/quoting#explanation):

> Whereas most databases will lowercase unquoted identifiers, Snowflake will uppercase unquoted identifiers. If a model name is lowercased and quoted, then it cannot be referred to without quotes!

### Workaround

Although it's not our [recommendation](https://docs.getdbt.com/reference/project-configs/quoting#recommendation), users can do the behavior you are describing by adding this to their `dbt_project.yml`:
```yaml
quoting:
  identifier: true
```

### Summary

Since dbt-snowflake is behaving the way we expect, and we don't plan on adding additional warnings at this time, I'm going to close this as "not planned".

**Closed** 2023-11-30 02:44 UTC
Labels: bug, wontfix
