### ISSUE TITLE
[ADAP-534] 1.5.0 is not available from conda-forge yet.

### ISSUE THREAD

**Issue by nevdelap** [dbt-labs/dbt-snowflake#601] opened 2023-05-09 23:44 UTC
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I asked about this in [Discussions](https://github.com/dbt-labs/dbt-snowflake/discussions/594) last week and since 1.5.0 has been out for two weeks...

dbt-snowflake 1.4.2 is available in conda-forge. https://anaconda.org/conda-forge/dbt-snowflake

### Expected Behavior

dbt-snowflake 1.5.0 should be available.

### Steps To Reproduce

Look at: https://anaconda.org/conda-forge/dbt-snowflake

Or try to install it.

```
> conda install -yq -c conda-forge --override-channels dbt-core=1.5.0 dbt-snowflake=1.5.0
<snip>
PackagesNotFoundError: The following packages are not available from current channels:
  - dbt-snowflake=1.5.0*
Current channels:
  - https://conda.anaconda.org/conda-forge
```

### Environment

```markdown
- OS: Ubuntu & Arch
- Python: Conda env with 3.9.
- dbt-core: 1.5.0
- dbt-snowflake: 1.5.0 🙏
```

**Comment by dbeatty10** [comment] 2023-05-10 01:22
@maresb or @rxm7706:
Do either of you know the procedure to get the latest versions of dbt-snowflake and dbt-redshift added to conda-forge?

Is it a PR that updates a line like [this](https://github.com/conda-forge/dbt-snowflake-feedstock/blob/c1ae8367ebc53c3f9044931a39cbef87049f462a/recipe/meta.yaml#L2) and [this](https://github.com/conda-forge/dbt-redshift-feedstock/blob/18b0d1977f21dbff92932a930599488816687d89/recipe/meta.yaml#L2)?

**Comment by maresb** [comment] 2023-05-10 07:19
Hey @dbeatty10, the procedure is slightly more involved, but usually mostly automated. We need to merge the bot-generated https://github.com/conda-forge/dbt-snowflake-feedstock/pull/8. Usually it's a simple matter of synchronizing the dependencies, but this time there was some weirdness with the `agate` package. I needed some time to look into it a bit further, and I got busy with other stuff. I'll take another quick look and see again if I can solve it quickly.

@nevdelap, for accuracy's sake, would you mind replacing "Anaconda" with "conda-forge" in the issue title and initial post? Anaconda actually refers to a _different_ repository where dbt isn't available at all. But it's confusing because Anaconda hosts conda-forge.

**Comment by dbeatty10** [comment] 2023-05-10 12:55
Thank you for your help and explanation on this @maresb ❤️

**Comment by maresb** [comment] 2023-05-10 13:04
In case there are issues with the conda-forge package being unavailable or uninstallable, the best place to get support is in the conda-forge feedstock repository of the respective package, in this case https://github.com/conda-forge/dbt-snowflake-feedstock.

If there is an open pull request to build the version in question, I'd recommend commenting there to ping the feedstock maintainers.

There's usually about 1h delay between when the package is built and when it becomes available on the CDN. So dbt-snowflake should have become installable, but it looks like there was some sort of transient failure during the final build. I'll nudge it...

**Comment by dbeatty10** [comment] 2023-05-10 13:27
> the best place to get support is in the conda-forge feedstock repository of the respective package, in this case https://github.com/conda-forge/dbt-snowflake-feedstock.

Perfect. Thank you for that guidance and this other useful explanation about the typical latency for CDN availability @maresb 🙏

**Comment by maresb** [comment] 2023-05-10 13:57
It's now available.

**Comment by dbeatty10** [comment] 2023-05-10 14:35
Thank you for closing the loop @maresb !

I double-checked and confirmed [here](https://anaconda.org/conda-forge/dbt-snowflake) and [here](https://anaconda.org/conda-forge/dbt-redshift).

<img width="400" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/9cb437ad-9006-4c30-9c43-1cd6f0c4bfb0">

<br/>

<img width="375" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/44704949/ddde924a-ba76-46eb-b0d8-4db8dd41136c">

**Closed by dbeatty10** 2023-05-10 14:35 UTC
Labels: bug

**Comment by nevdelap** [comment] 2023-05-10 21:00
Thank you guys!
