### ISSUE TITLE
Installing 1.7.3 on Airflow 2.9

### ISSUE THREAD

**Issue by tanmaykansara** [dbt-labs/dbt-snowflake#968] opened 2024-04-11 09:20 UTC
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Here is my requirements.txt:
`
apache-airflow-providers-amazon==8.19.0
pymssql==2.2.11
snowflake-connector-python==3.7.1
pytest==7.4.4
snowflake-snowpark-python==1.14.0
cachetools==5.3.3
regex==2023.12.25
scikit-learn==1.4.1.post1
dbt-snowflake==1.7.0
`

and here is the dockerfile pip install command:
`
FROM apache/airflow:2.9.0-python3.10
COPY requirements.txt /
RUN pip install  --force-reinstall --no-cache-dir -r /requirements.txt  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.10.txt"

`

Whenever I build the docker container I get the following errors:
`61.28 ERROR: Cannot install apache-airflow-providers-amazon because these package versions have conflicting dependencies.
61.28
61.28 The conflict is caused by:
61.28     apache-airflow 2.8.4 depends on flask-appbuilder==4.3.11
61.28     apache-airflow 2.8.3 depends on flask-appbuilder==4.3.11
61.28     apache-airflow 2.8.2 depends on flask-appbuilder==4.3.11
61.28     apache-airflow 2.8.1 depends on flask-appbuilder==4.3.10
61.28     apache-airflow 2.8.0 depends on flask-appbuilder==4.3.10
61.28     apache-airflow 2.7.3 depends on WTForms<3.1.0
61.28     apache-airflow 2.7.2 depends on flask-appbuilder==4.3.6
61.28     apache-airflow 2.7.1 depends on flask-appbuilder==4.3.6
61.28     apache-airflow 2.7.0 depends on flask-appbuilder==4.3.3
61.28     apache-airflow 2.6.3 depends on flask-appbuilder==4.3.1
61.28     apache-airflow 2.6.2 depends on flask-appbuilder==4.3.1
61.28     apache-airflow 2.6.1 depends on flask-appbuilder==4.3.0
61.28     apache-airflow 2.6.0 depends on flask-appbuilder==4.3.0
61.28     The user requested (constraint) flask-appbuilder==4.4.1
61.28     The user requested (constraint) wtforms==3.1.2`

If I remove the last line in the requirements.txt file and run the docker build, everything runs fine. Is there a specific version of dbt-snowflake that is compatible with Airflow 2.9 ?

Thanks

### Expected Behavior

dbt-snowflake should beinstalled 

### Steps To Reproduce

use the specified dockerfile, and requirements.txt to spin up airflow

### Environment

```markdown
- OS:any
- Python: 3.10
- dbt-core:
- dbt-snowflake: 1.7.3
```

**Comment by dataders** [comment] 2024-04-15 15:34
Hi @tanmaykansara -- sorry to hear you're having difficulties. We've certainly heard users mention this before.

By chance, are you following instructions from [aws-mwaa-local-runner](https://github.com/aws/aws-mwaa-local-runner) and using their Dockerfile definition? If so, please respond to my just opened https://github.com/aws/aws-mwaa-local-runner/issues/371 to share you concerns.

For now, I'm going to close as a duplicate of #687 (and https://github.com/dbt-labs/dbt-redshift/issues/700)

**Closed by dataders** 2024-04-15 15:34 UTC
Labels: bug
