### ISSUE TITLE
[CT-1619] [Bug] Could not connect to Snowflake backend after 0 attempt(s)

### ISSUE THREAD

**Issue by kirill-andr** [dbt-labs/dbt-snowflake#70] opened 2021-12-16 20:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

post upgrade to 1.0.0 dbt cli is not connecting to snowflake

### Expected Behavior

connect to snowflake after running dbt debug

### Steps To Reproduce

Upgrade to dbt 1.0.0
execute `dbt debug`

### Relevant log output

```shell
20:30:54  Running with dbt=1.0.0
dbt version: 1.0.0
python version: 3.9.9
python path: /usr/local/Cellar/dbt-snowflake/1.0.0/libexec/bin/python3.9
os info: macOS-12.0.1-x86_64-i386-64bit
Using profiles.yml file at /Users/me/.dbt/profiles.yml
Using dbt_project.yml file at /Users/me/Documents/Intellij Projects/gl/dbt/dbt_project.yml

Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]

Required dependencies:
 - git [OK found]

Connection:
  account: ********
  user: ********
  database: ********
  schema: ********
  warehouse: ********
  role: ********
  client_session_keep_alive: False
  Connection test: [ERROR]

1 check failed:
dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  250001: Could not connect to Snowflake backend after 0 attempt(s).Aborting

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile
```

### Environment

```markdown
- OS:MacOS Monterey
- Python: 3.9.9
- dbt: 1.0.0
```

### What database are you using dbt with?

snowflake

### Additional Context

I have upgraded via homebrew to dbt 1.0.0 and just like that all connections to snowflake stopped working.

**Comment by jtcohen6** [comment] 2021-12-16 21:31
@kirill-andr Which connection method are you using with Snowflake? And which version of `snowflake-connector-python` do you have installed (you can check using `pip freeze`)?

This error message is coming from the `handle_timeout` method in one of two places in the Snowflake python connector:
- [auth by plugin](https://github.com/snowflakedb/snowflake-connector-python/blob/041cbb15b75c8b0093496e17b44c2e95334d6881/src/snowflake/connector/auth_by_plugin.py#L117-L120) (a.k.a. `authenticator: externalbrowser`)
- [auth by key pair](https://github.com/snowflakedb/snowflake-connector-python/blob/041cbb15b75c8b0093496e17b44c2e95334d6881/src/snowflake/connector/auth_keypair.py#L175-L179)

I did some quick searching for where the same error message has cropped up elsewhere. In [this SO post](https://stackoverflow.com/questions/70187732/snowflake-connector-errors-operationalerror-250003-failed-to-get-the-response), it looks like it was related to a proxy or SSL configuration:

> There was a security certificate issue from my organization . Importing the SSL certificate fixed the issue.

**Comment by kirill-andr** [comment] 2021-12-17 05:19
I have added the credentials for snowflake in the profiles.yml and I am using the username and password authentication. I am doubtful there is a proxy or other configuration outside of DBT that is affecting it because hours prior to upgrading DBT the connection to 3 different Snowflake accounts worked perfectly. After upgrade from 0.10 to 1.0.0 all projects are unable to connect any longer.

**Comment by jtcohen6** [comment] 2021-12-17 09:25
@kirill-andr I'd like to get to the bottom of whether this bug is coming from:
- a change in `dbt-snowflake`
- a change in `snowflake-connector-python` (which is where this error is coming from)

To that end, are you able to identify the version of `snowflake-connector-python` that you're using before and after upgrading dbt? Or try installing an older version of `snowflake-connector-python` alongside `dbt-snowflake==1.0.0`?

**Comment by kirill-andr** [comment] 2021-12-17 10:54
@jtcohen6 just installed and linked  dbt-snowflake@1.0.0-b1 and it works just fine. Must be something with  dbt-snowflake@1.0.0

**Comment by jtcohen6** [comment] 2021-12-17 11:05
Ok, that's helpful!

[These are the changes](https://github.com/dbt-labs/dbt-snowflake/compare/22826ab37e9227cd322ee9b1c2b463c4f5a3dc3e...13b48431c79377632b7dcdc0716b4204425d29f3) `1.0.0-b1` and `1.0.0`. The ones that I think might be relevant here:
- https://github.com/dbt-labs/dbt-snowflake/commit/a4edd8e8b97d17177548ea029f479006dc5504b7 added support for retries, but using new optional configs (`retry_on_database_errors`, `retry_all`, `connect_retries`, `connect_timeout`) that you don't have defined 
- https://github.com/dbt-labs/dbt-snowflake/commit/aaffcd0760fba11013c3e2e66167379bf26402c7 raised the upper limit on `snowflake-connector-python` to allow `2.7.*`. It looks like `snowflake-connector-python==2.7.2` included a fix (https://github.com/snowflakedb/snowflake-connector-python/pull/919) for JWT keypair expiration, which added the `Could not connect to Snowflake backend` error message that you're now seeing.

Could you try installing v1.0.0 of `dbt-snowflake` with the previous version of `snowflake-connector-python`?
```
pip install "snowflake-connector-python<2.7.2" dbt-snowflake==1.0.0
```
If that fixes the issue for you, it would strongly suggest that the root cause of this bug lies in that change.

**Comment by Nathancalon** [comment] 2021-12-18 13:34
I've just installed and had the same issue (this is under Mac silicon with rosetta, which I have had issues with before but never finally fixed). 

I just tried that install you suggested and it fails again. Really getting annoyed with dbt now, it just never seems to work with Snowflake on my Mac

**Comment by kirill-andr** [comment] 2021-12-18 14:17
@Nathancalon I rolled back to dbt 0.21 and it worked well. I will stay with this version for now.

**Comment by anthu** [comment] 2021-12-18 16:00
What region are you in?
Please refer to this list on how to provide the Account identifier:
https://docs.snowflake.com/en/user-guide/admin-account-identifier.html#account-identifier-formats-by-cloud-platform-and-region

Some of the regions don't require the **cloud** identifier.

**Comment by Nathancalon** [comment] 2021-12-18 16:08
Thanks  - Europe/Frankfurt - it doesn’t
Thanks for the help. Everything is working now.

**Comment by lmmentel** [comment] 2022-02-07 12:25
I'm experiencing the same issue on
- linux mint 
- python 3.9.9

```
dbt-core                   1.0.1     With dbt, data analysts and engineers can build analytics the way engineers build applications.
dbt-snowflake              1.0.0     The Snowflake adapter plugin for dbt
snowflake-connector-python 2.7.4     Snowflake Connector for Python
```

Should I downgrade?

**Comment by lmmentel** [comment] 2022-02-07 13:23
> // edit - I had followed the instruction to put .aws at the end of the connection but removing it connected ok.

I can confirm that removing the `aws` at the end of the `account` string makes the connection succeed. thanks @Nathancalon

**Comment by klayhb** [comment] 2022-05-26 11:28
this still does not work for us and i'm getting this error on credentials that a moment ago worked just fine in version 0.19... any help please?

**Comment by anthu** [comment] 2022-05-26 12:27
what is your `account` setting and what URL are you using to connect to Snowflake via the browser? 

Feel free to redact the accountId (eg. `xxxxx.us-east-2.aws`).

**Comment by anthu** [comment] 2022-05-26 15:14
Anything suspicious in `logs/dbt.log`?
What do you see running `dbt debug`?

Really hard to tell what's wrong here. I'm about to try to reproduce it - so long please help me out with your findings.

**Comment by klayhb** [comment] 2022-05-26 15:51
dbt debug output doesn't offer much more information:

```
12:01:07.132543 [debug] [ThreadPool]: Opening a new connection, currently in state init
12:01:07.134290 [debug] [ThreadPool]: Opening a new connection, currently in state init
12:10:11.594691 [debug] [ThreadPool]: Snowflake adapter: Got an error when attempting to open a snowflake connection. No retries attempted: '250001: Could not connect to Snowflake backend after 0 attempt(s).Aborting'
12:10:11.595565 [debug] [ThreadPool]: Snowflake adapter: Got an error when attempting to open a snowflake connection. No retries attempted: '250001: Could not connect to Snowflake backend after 0 attempt(s).Aborting'
```

So seems like it took it about 10 minutes to get to that error state (which is weird in itself)


Same exact thing appears in the `logs/dbt.log`

**Comment by klayhb** [comment] 2022-05-26 16:43
Fixed the issue!
issue was a "remnant" PORT configuration in our `profiles.yml` file from an earlier version of dbt which supported "host" and "port". Apparently it was harmless throughout 0.19 and 0.20 but started interfering in 1.0.0 onwards.

once removed, connection worked again

**Comment by sgurwex** [comment] 2022-09-19 22:01
To fix / resolve this, all I had to do was add the .gcp to the end of the account property of the profiles.yml file. For example:

account: xx12345.us-central1.gcp instead of :
account: xx12345.us-central1

**Comment by Fleid** [comment] 2022-12-06 22:56
Closing as it looks resolved

**Closed by Fleid** 2022-12-06 22:56 UTC
Labels: jira
