### ISSUE TITLE
[CT-1479] [Regression] Invalid Number Precision error for incremental model in 1.3

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-snowflake#312] opened 2022-11-07 12:26 UTC
### Is this a regression in a recent version of dbt-snowflake?

- [X] I believe this is a regression in dbt-snowflake functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Running an incremental refresh on a new column with number(38,0) causes breakages, as number(39,0) is not a valid column type.

This seems to be for `sync_all_columns`, `ignore` works.

### Expected/Previous Behavior

It works :)

### Steps To Reproduce

See https://github.com/dbt-labs/dbt-core/issues/6107 for a summary on how to reproduce, thanks to @kellyldougan for the great easy to reproduce example.

### Environment

```markdown
- OS: Linux
- Python: 3.10
- dbt-core (working version): 1.2
- dbt-snowflake (working version): 1.2
- dbt-core (regression version): 1.3 and above
- dbt-snowflake (regression version): 1.3 and above
```

**Comment by dbeatty10** [comment] 2022-11-15 16:18
@joshuataylor thank you for reporting this! Very helpful to know that `ignore` works but `sync_all_columns` does not.

To keep things as organized as possible, I'm going to close this as a duplicate of https://github.com/dbt-labs/dbt-core/issues/6107 which I see you are participating in.

**Closed by dbeatty10** 2022-11-15 16:18 UTC
Labels: bug, triage
